spring:
  application:
    name: jpa-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update  # Change to 'update' or 'create' if needed
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081