spring:
  h2:
    console:
      enabled: true

  application:
    name: prototype-scope-example
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  profiles:
    active: test

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

