spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kattyavar-shika/microservice-demo-config
          clone-on-start: true
