spring:
  application:
    name: config-

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kattyavar-shika/microservice-demo-config
          clone-on-start: true
app:
  kattyavar:
    shika:
      name: config Demo
      version: 1.0.0
      description: you can put anything no issues.
      profile: dev